# Embedded Tomcat Server Port
server.port=${PORT:8080}

# PostgreSQL Configuration (Local)
spring.datasource.url=jdbc:postgresql://dpg-d7ghc7hj2pic73bh3lc0-a.singapore-postgres.render.com:5432/campusconnect_db_u57c
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=campusconnect_db_u57c_user
spring.datasource.password=qgaw929e1bZoOvM97vMcYkDTBnhTsMxI

# JPA / Hibernate Configuration
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true